{
 "title": "firs dash",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WebTours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "win_services",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "WebTours" }
     ]
    }
   ]
  },
  {
   "title": "% Processor Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Committed Bytes In Use",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "select": [
      [
       { "params": [ "Percent_Disk_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Total persec",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Bytes_Total_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Total persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Processor Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Processor time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Privileged TIme",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Privileged TIme" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processor Queue Lenght",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Processor_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Processor Queue Lenght" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% DPC time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_DPC_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% DPC time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% User Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_User_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% User Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "% Available Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Available Bytes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Committed Bytes In Use",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Committed_Bytes_In_Use" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Committed_Bytes_In_Use" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages_persec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Pages_persec\") AS \"Pages_persec\" FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Pages_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Pages_persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Privileged TIme",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Privileged_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Privileged TIme" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Page Faults persec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "query": "SELECT mean(\"Percent_Committed_Bytes_In_Use\") FROM \"win_mem\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Page_Faults_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Page Faults persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Disk Read Bytes persec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Read_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk Read Bytes persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Write Bytes persec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_diskio",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Disk_Write_Bytes_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Disk Write Bytes persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Disk Queue lenght",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Current Disk Queue lenght" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Free space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Free_Space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Disk Free space" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Read Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Read_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Disk Read Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Write Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Write_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Disk Write Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Disk Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% Disk Time" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Bytes Total persec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Bytes_Total_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Total persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Received persec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Received persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Sent persec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Localhost, $measurement, $col",
     "groupBy": [
      { "params": [ "3s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Disk_Read_Bytes_persec\") AS \"% Disk Read Time\" FROM \"win_diskio\" WHERE $timeFilter GROUP BY time(3s) fill(null)",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Sent persec" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}